### ISSUE TITLE
how to apply branding/corporate design to the signup-portal webapp?

### ISSUE THREAD

**Issue by rkrenn** [phoenixctms/ctsms#174]
aside the phoenix CTMS jee webapp, there is the customer-facing webapplication for subject candidates to register themselves.

![grafik](https://user-images.githubusercontent.com/17864099/121756940-3560ef00-cb1c-11eb-9566-026d5e3cdb88.png)

it has some blank default style/"MyCRO" branding, how can we adopt that to our corporate webpage designs?

**Comment by rkrenn** [comment]
the Signup Portal uses an workflow comprising of 6 steps: 

1. Page#1 "start": Start, Site Selection -> 
2. Page#2 "proband": Consent Agreement with Name&DoB ->
3. Page#3 "contact details": Provide Contact Details (Address, Mail, Phone) ->
4. Page#4 "trials": [OPTIONAL] Select&ensign for Trials ->
5. Page#5 "inquiry form": [OPTIONAL] Fill out Inquiry Forms of Trials ->
6. Page#6 "end": Finish, print Registration Details

each step corresponds to a separate page, between the candidate can jump back and forth. while the sequence is considered fixed, you can override the appearance of each page using TT (http://www.template-toolkit.org/) templates and choosing one of 30 PriumeUI themes. The default "MyCRO" example can be found at https://github.com/phoenixctms/config-default/tree/master/bulk_processor/CTSMS/BulkProcessor/Projects/WebApps/Signup/views . So you would usually also include your own stylesheets & media, to align your corporate design.

Example of customized Page#1 "start":

![grafik](https://user-images.githubusercontent.com/17864099/124617114-f867ee00-de76-11eb-925d-1fc80d4690f7.png)

Example of customized Page#5 "inquiry form":

![grafik](https://user-images.githubusercontent.com/17864099/124617215-0ae22780-de77-11eb-96a7-2d1925b2544e.png)

internationalization is supported via MakeText. The .po files (https://www.gnu.org/software/gettext/manual/html_node/PO-Files.html) found in https://github.com/phoenixctms/config-default/tree/master/bulk_processor/CTSMS/BulkProcessor/Projects/WebApps/Signup/i18n .

The Sites presented on the Start page can be defined in https://github.com/phoenixctms/config-default/blob/master/bulk_processor/CTSMS/BulkProcessor/Projects/WebApps/Signup/settings.yml:

```
ctsms_sites:
  '00_my_department':
    label: 'My Department'
#    uri:
    default: 1
#    mass_mail:
#      de: 6552634
#      en: 6552637
    trial_signup: 1
    register: 1
    default_geolocation_latitude: 47.081424
    default_geolocation_longitude: 15.468107
    show_map: 0
    description: '<b>My CRO</b></br>My Department</br>Evergreen Terrace 123, 12345 Springfield</br>Mo. – Fr. 08:00-16:00</br>Tel.: 01/123 45678</br>Mail: <a href="mailto:mydepartment@mycro.com?subject=Signup">mydepartment@mycro.com</a>'
    department: 'my_department'
#    trial_department: 'my_department'
    trial_department:
#    inquiry_trial: 238743
    phone_contact_detail_type: 'business_phone_number'
    email_contact_detail_type: 'business_email_address'
    address_type: 'business'
    credentials:
      de:
        username: 'my_department_signup_de'
        password: 'my_department_signup_de'
      en:
        username: 'my_department_signup_en'
        password: 'my_department_signup_en'
```
